import { FilterContextProvider } from "@/context/filterContext";
import Header from "./components/Header/header";
import "./globals.css";
import { Saira } from "next/font/google";

const saira = Saira({
    subsets: ["latin"],
    weight: ["400", "500", "600"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={saira.className} suppressHydrationWarning={true}>
                <FilterContextProvider>
                    <Header />
                    {children}
                </FilterContextProvider>
            </body>
        </html>
    );
}
